
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6] #, 3.7, 3.8]
        # on: [macos-latest] #, macos-latest, windows-latest]
        on: [ubuntu-16.04] #

    runs-on: ${{ matrix.on }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip

      - name: Install tools dependencies
        run: |
          make tools

      - name: make
        run: |
          make
