# (C) Copyright 2020 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # TODO: prepare the docker image:
  # https://docs.github.com/en/actions/guides/publishing-docker-images
  # https://github.com/marketplace/actions/build-docker-images-using-cache

jobs:
  build-manylinux2014:

    # if: false

    runs-on: ubuntu-latest
    container:  dockcross/manylinux2014-x64:latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6"]  # ["3.6", "3.7", "3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Create docker image
      #   run: |
      #     make dockcross-build-ecmwflibs

      - name: Install tools dependencies
        run: |
          make tools

      # - name: Cache compilations (src)
      #   uses: actions/cache@v2
      #   with:
      #     path: src
      #     key: ${{ runner.os }}-src-${{ hashFiles('make/VERSIONS.make') }}

      # - name: Cache compilations (build)
      #   uses: actions/cache@v2
      #   with:
      #     path: build-ecmwf
      #     key: ${{ runner.os }}-build-ecmwf-${{ hashFiles('make/VERSIONS.make') }}

      # - name: Cache compilations (install)
      #   uses: actions/cache@v2
      #   with:
      #     path: install
      #     key: ${{ runner.os }}-install-${{ hashFiles('make/VERSIONS.make') }}

      - name: make pango/cairo
        run: |
          make pango

      - name: make proj
        run: |
          make proj

      - name: make libraries
        # if: false
        run: |
          make libraries

      - name: make wheel
        # if: false
        run: |
          make wheel

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-manylinux2014
          path: wheelhouse/*
