# (C) Copyright 2020 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # if: false

    runs-on: ubuntu-latest
    container:  dockcross/manylinux2014-x64:latest


    name: Build manylinux2014-x64

    steps:
      - uses: actions/checkout@v2

      - run: make tools

      - name: Cache compilations
        # if: false
        uses: actions/cache@v2
        with:
          path: |
            src
            build-ecmwf
            install
          key: ${{ runner.os }}-cache-${{ hashFiles('make/VERSIONS.make') }}

      - run: make pull
      - run: make wheels

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-manylinux2014-3.6
          path: wheelhouse/*cp36*

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-manylinux2014-3.7
          path: wheelhouse/*cp37*

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-manylinux2014-3.8
          path: wheelhouse/*cp38*

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-manylinux2014-3.9
          path: wheelhouse/*cp39*

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.7", "3.8", "3.9"]

    name: Test with Python ${{ matrix.python-version }}

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v2
        with:
          name: wheel-manylinux2014-${{ matrix.python-version }}

      - run: pip install *.whl

      - run: pip install -r tests/requirements.txt

      - run: pip freeze

      - name: Get data.grib
        run: curl -o tests/data.grib http://download.ecmwf.int/test-data/magics/2m_temperature.grib

      - run: pytest -v -s
        working-directory: tests

      - uses: actions/upload-artifact@v2
        with:
          name: tests-manylinux2014-${{ matrix.python-version }}
          path: tests/*.png
