
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:

    runs-on: macos-latest
    # if: false

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip

      - name: Install tools dependencies
        run: |
          make tools

      - name: Cache compilations (src)
        uses: actions/cache@v2
        with:
          path: src
          key: ${{ runner.os }}-src

      - name: Cache compilations (build)
        uses: actions/cache@v2
        with:
          path: build-ecmwf
          key: ${{ runner.os }}-build-ecmwf

      - name: Cache compilations (install)
        uses: actions/cache@v2
        with:
          path: install
          key: ${{ runner.os }}-install

      - name: make libraries
        run: |
          make libraries

      - name: make wheel
        run: |
          make wheel

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-macos
          path: wheelhouse/*


  # TODO: prepare the docker image:
  # https://docs.github.com/en/actions/guides/publishing-docker-images
  build-manylinux2014:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create docker image
        run: |
          make dockcross-build-ecmwflibs

      - name: Install tools dependencies
        run: |
          ./dockcross-build-ecmwflibs make tools

      - name: Cache compilations (src)
        uses: actions/cache@v2
        with:
          path: src
          key: ${{ runner.os }}-src-2

      - name: Cache compilations (build)
        uses: actions/cache@v2
        with:
          path: build-ecmwf
          key: ${{ runner.os }}-build-ecmwf-2

      - name: Cache compilations (install)
        uses: actions/cache@v2
        with:
          path: install
          key: ${{ runner.os }}-install-2

      - name: make pango/cairo
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./dockcross-build-ecmwflibs make pango

      - name: make proj
        run: |
          ./dockcross-build-ecmwflibs make proj

      - name: make libraries
        run: |
          ./dockcross-build-ecmwflibs make libraries

      - name: make wheel
        run: |
          ./dockcross-build-ecmwflibs make wheel

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-manylinux2014
          path: wheelhouse/*


  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip

      - name: Install tools dependencies
        run: |
          make tools

      - name: eccodes
        run: |
          make eccodes

      - uses: actions/upload-artifact@v2
        if: false
        with:
          name: wheel-windows
          path: wheelhouse/*
