
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:

    runs-on: macos-latest
    if: false

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip

      - name: Install tools dependencies
        run: |
          make tools

      - name: Cache compilations (src)
        uses: actions/cache@v2
        with:
          path: src
          key: ${{ runner.os }}-src

      - name: Cache compilations (build)
        uses: actions/cache@v2
        with:
          path: build-ecmwf
          key: ${{ runner.os }}-build-ecmwf

      - name: Cache compilations (install)
        uses: actions/cache@v2
        with:
          path: install
          key: ${{ runner.os }}-install

      - name: make libraries
        run: |
          make libraries

      - name: make wheel
        run: |
          make wheel

  build-manylinux2014:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create docker image
        run: |
          make dockcross-build-ecmwflibs

      - name: Install tools dependencies
        run: |
          ./dockcross-build-ecmwflibs make tools

      # - name: Cache compilations (src)
      #   uses: actions/cache@v2
      #   with:
      #     path: src
      #     key: ${{ runner.os }}-src

      # - name: Cache compilations (build)
      #   uses: actions/cache@v2
      #   with:
      #     path: build-ecmwf
      #     key: ${{ runner.os }}-build-ecmwf

      # - name: Cache compilations (install)
      #   uses: actions/cache@v2
      #   with:
      #     path: install
      #     key: ${{ runner.os }}-install

      - name: make libraries
        run: |
          ./dockcross-build-ecmwflibs make libraries

      - name: make wheel
        run: |
          ./dockcross-build-ecmwflibs make wheel

  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip

      - name: Install tools dependencies
        run: |
          make tools
