# (C) Copyright 2020 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-windows:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    name: Python ${{ matrix.python-version }}

    steps:


      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache install tools
        uses: actions/cache@v2
        with:
          path: c:\vcpkg
          key: ${{ runner.os }}-install-tools-${{ hashFiles('make/tools-windows.make') }}


      - name: Install tools dependencies
        run: |
          make tools

      - name: Cache compilations (src)
        uses: actions/cache@v2
        with:
          path: src
          key: ${{ runner.os }}-src-${{ hashFiles('make/VERSIONS.make') }}

      - name: Cache compilations (build)
        uses: actions/cache@v2
        with:
          path: build-ecmwf
          key: ${{ runner.os }}-build-ecmwf-${{ hashFiles('make/VERSIONS.make') }}

      - name: Cache compilations (install)
        uses: actions/cache@v2
        with:
          path: install
          key: ${{ runner.os }}-install-${{ hashFiles('make/VERSIONS.make') }}

      - name: make libraries
        env:
          PYTHONPATH: c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages
        run: |
          make libraries

      - name: make wheel
        # if: false
        run: |
          make wheel

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-windows-${{ matrix.python-version }}
          path: dist/*

      - name: depends
        continue-on-error: true
        run: |
          dlldiag deps ecmwflibs/MagPlus.dll
