# (C) Copyright 2020 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-windows:

    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6"] #, "3.7", "3.8"]
        architecture: ["x86"] #, "x64"]

    name: Python ${{ matrix.python-version }} ${{ matrix.architecture }}
    env:
      WINARCH: ${{ matrix.architecture }}

    steps:

      - uses: actions/checkout@v2

      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: ${{ matrix.architecture }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Cache install tools
        uses: actions/cache@v2
        with:
          path: c:\vcpkg
          key: ${{ runner.os }}${{ matrix.architecture }}-tools-${{ hashFiles('make/tools-windows.make') }}

      - run: make tools

      - name: Cache compilations
        if: false
        uses: actions/cache@v2
        with:
          path: |
            src
            build-ecmwf
            install
          key: ${{ runner.os }}${{ matrix.architecture }}-cache-${{ hashFiles('make/VERSIONS.make') }}

      - run: make wheel

      # - name: debug
      #   run: cat D:\a\ecmwflibs\ecmwflibs\build-ecmwf\eccodes\memfs\memfs_gen_001.c
      #   continue-on-error: true

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-windows-${{ matrix.python-version }}-${{ matrix.architecture }}
          path: dist/*
