# (C) Copyright 2020 ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

name: Build MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: make tools

      - name: Cache compilations
        uses: actions/cache@v2
        with:
          path: |
            src
            build-ecmwf
            install
          key: ${{ runner.os }}-cache-${{ hashFiles('make/VERSIONS.make') }}

      - run: make

      - uses: actions/upload-artifact@v2
        with:
          name: wheel-macos-${{ matrix.python-version }}
          path: wheelhouse/*
