name: test

on: push

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        container:
        - 'dockcross/manylinux1-x64'
        - 'dockcross/manylinux2010-x64'
        - 'dockcross/manylinux2014-x64'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: cat /etc/*release
      # - run: yum update -y
      # - run: yum install -y nodejs
      - uses: actions/checkout@v1 # v2 does not work on all platforms
