name: test

on: push

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        container:
        - 'debian:7'
        - 'debian:testing'
        - 'ubuntu:14.04'
        - 'ubuntu:devel'
        - 'centos:6'
        - 'centos:latest'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: cat /etc/*release
      - run: yum install -y node
      - uses: actions/checkout@v2
