name: test

on: push
  # release:
  #   types: [created]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        container:
        - 'dockcross/manylinux1-x64'
        - 'dockcross/manylinux2010-x64'
        - 'dockcross/manylinux2014-x64'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v1

      - run: |
          mkdir -p dockcross
          echo ${{ matrix.container }} > ${{ matrix.container }}.txt

      # actions/upload-artifact@v1 does not support wildcards
      - name: Get paths
        id: get-paths
        run: |
          echo "::set-output name=WHEEL_36::$(ls dockcross/*)"

      - uses: actions/upload-artifact@v1
        name: Upload wheel 3.6
        with:
          name: art-${{ matrix.container }}
          path: ${{ steps.get-paths.outputs.WHEEL_36 }}
